- name: Install Caddy
  ansible.builtin.apt:
    update_cache: true
    name: caddy
    state: present

- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0644"

- name: Restart Caddy
  ansible.builtin.service:
    name: caddy
    state: restarted
    enabled: true

